  socket_host: "localhost"
  socket_port: 8017
  http:
    enabled: true
    port: 8080
  ws:
    enabled: true
    port: 8019
  sai_crypto_address: "127.0.0.1:8085"
  storage_token: "12345"
  trusted_validators: []
  sleep: 2
  storage_url: "http://127.0.0.1:8801"
  storage_email: "ddd@mial.com"
  storage_password: "fdfsdf"
  saiBTC_address: "http://127.0.0.1:3305"
  saiP2P_address: "http://127.0.0.1:8071/send" ## proxy, not saip2p
  log_mode: "debug"