version: '3'
services:
  sai-btc:
    build:
      context: ./saiBtc
      dockerfile: Dockerfile
    ports:
      - "3305:3305"
       
  sai-storage:
    build:
      context: ./saiStorage
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
      - "8801:8801"
      - "8802:8802"
      
  sai-bft:
    build:
      context: ./saiBft
      dockerfile: Dockerfile
    ports:
      - "8017:8017"
      - "8018:8018"
      - "8019:8019"

  sai-p2p:
    build:
      context: ./saiP2p
      dockerfile: Dockerfile
    ports:
      - "8071:8071"

      
      
